server_name: server-room-nats

port: 4222

http_port: 8222

jetstream {
    store_dir: "/data"
}

websocket {
    port: 9222
    no_tls: true
}

authorization {
    users = [
        {
            user: "temperature-writer"
            password: "CHANGE-ME-WRITER"

            permissions = {
                publish = [
                    "serverroom.temperature.room1.sensor1"
                ]
                subscribe = []
            }
        }

        {
            user: "temperature-reader"
            password: "CHANGE-ME-READER"

            permissions = {
                publish = []
                subscribe = [
                    "serverroom.temperature.>"
                ]
            }
        }

        {
          user: "temperature-dashboard"
          password: "CHANGE-ME-DASHBOARD"
          permissions: {
            publish = []
            subscribe = [
              "serverroom.temperature.>"
              "_INBOX.>"
            ]
          }
        }

        {
          user: "temperature-admin"
          password: "CHANGE-ME-ADMIN"

          permissions {
            publish = ">"
            subscribe = ">"
          }
        }

    ]
}
