{{- $persistence := .Values.nats.persistence | default .Values.persistence }}
{{- if and .Values.nats.enabled $persistence $persistence.enabled (not $persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nats-data
  labels:
    {{- include "server-room.natsLabels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml $persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ $persistence.size }}
  {{- $storageClass := $persistence.storageClass | default $persistence.storageClassName }}
  {{- if $storageClass }}
  {{- if (eq "-" $storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
