{{- if and .Values.nats.enabled .Values.nats.authorization.enabled (not .Values.nats.authorization.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-nats-auth
  labels:
    {{- include "server-room.natsLabels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $i, $user := .Values.nats.authorization.users }}
  NATS_USER_PASSWORD_{{ $i }}: {{ required (printf "password is required for nats.authorization.users[%d]" $i) $user.password | quote }}
  {{- end }}
{{- end }}
